# ==============================================================
# WAX CONFIGURATION
# ==============================================================
# Jekyll configuration files are written in YAML format.
# Colons, tabs/spacing, and quotes are meaningful in YAML.
# It is recommended you look at the following guide to avoid
# syntax errors in this file:
# ~> https://learnxinyminutes.com/docs/yaml/
#
#
# Questions ?
# ~> https://minicomp.github.io/wiki/#/
# ~> https://gitter.im/minicomp/wax/
#
# ---------------------------------------------------------------
# MAIN SETTINGS
# ---------------------------------------------------------------
# Feel free to change these! For more info, refer to:
# ~> https://jekyllrb.com/docs/configuration/options/

title:            'COMPARISON, AFFECTS, & POWER'
description:      ''
url:              'https://maxjdugan.github.io'
baseurl:          '/comparing_affects'
copyright:        'Max Johnson Dugan & Heather Radwan Jaber, 2022'
logo:             #old formatting: '/assets/logo.png'

# ---------------------------------------------------------------
# BUILD SETTINGS
# ---------------------------------------------------------------
# Best not to mess with these unless you know what you're doing!

permalink: 'pretty'
sass:
  style: compressed
exclude:
  - Gemfile*
  - Rakefile
  - vendor
  - spec
  - README.md
incremental: true
webrick:
  headers:
    'Access-Control-Allow-Origin': '*'
kramdown:
 auto_ids:       true
 footnote_nr:    1
 entity_output:  as_char
 footnote_backlink: "&#x21a9;&#xfe0e;"
 toc_levels:     1..6
 smart_quotes:   lsquo,rsquo,ldquo,rdquo
 enable_coderay: false


# --------------------------------------------------------------
# COLLECTION SETTINGS
# --------------------------------------------------------------
# Wax leverages Jekyll collections for much of its
# functionality, therefor some of the keys below are from
# Jekyll while others are Wax-specific.
# For more info, refer to:
# ~> https://jekyllrb.com/docs/collections/

collections:
  exhibits:
    output: true
  ca_archive: # name of collection
    output: true # makes sure pages are output as html files
    layout: 'ca_archive_item' # the layout for the pages to use
    metadata:
      source: 'comparing_affects_archive.csv' # path to the metadata file within `_data`
    images:
      source: 'raw_images/ca_archive' # path to the directory of images within `_data`

# --------------------------------------------------------------
# SEARCH INDEX SETTINGS
# --------------------------------------------------------------
# You can create multiple search indexes below (though only one is
# recommended!) by specifying
# an `index` file to write it to and some `collections` for it to index
# and running `$ bundle exec rake wax:search` .

search:
  main:
    index: '/search/index.json' # file the index will get written to
    collections:
      ca_archive:
        content: false # whether or not to index page content
        fields: # the metadata fields to index
          - label
          - creator
          - source
          - _date
          - description
          - url_original
          - url_video
          - attribution

# --------------------------------------------------------------
# SITE MENU SETTINGS
# --------------------------------------------------------------
# Each menu item needs a `label` (whats shown), and a `link`
# (where it goes). An item can optionally have a dropdown
# submenu via `sub`.

menu:
  - label: 'cfp'
    link: '/cfp/'
  - label: 'schedule'
    link: '/schedule/'
  - label: 'contact'
    link: '/contact/'
  - label: 'archive'
#    sub:
#      - label: 'collection'  
#        link: '/collection/'
#      - label: 'search'
#        link: '/search/'
#      - label: 'reuse'
#        link: '/reuse/'

# --------------------------------------------------------------
# SITE FOOTER SETTINGS
# --------------------------------------------------------------
#

footer:
  links:
    - label: 'GitHub'
      link: 'https://github.com/maxjdugan/comparing_affects'
    - label: 'Credits'
      link: '/credits'
    - label: 'Contact'
      link: 'mailto:comparing.affects@gmail.com'
  logos:
    - img: '/img/logo.png'

# FIN
